services:
  postgres:
    image: postgres:17
    container_name: adi-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - adi_postgres_data:/var/lib/postgresql/data

volumes:
  adi_postgres_data:
