"""create trial balance zone tables

Revision ID: ad2fef0348c1
Revises: f990fd3dad64
Create Date: 2026-08-24 18:49:52.025518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2fef0348c1'
down_revision: Union[str, Sequence[str], None] = 'f990fd3dad64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'trial_balance',

        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('extract_dt', sa.Date(), nullable=False),
        sa.Column('as_of_dt', sa.Date(), nullable=False),
        sa.Column('business_dt', sa.Date(), nullable=False),
        sa.Column('src_app_cd', sa.String(), nullable=False),
        sa.Column('src_app_nm', sa.String(), nullable=False),
        sa.Column('dataclass', sa.String(), nullable=True),
        sa.Column('src_record_id', sa.String(), nullable=False),
        sa.Column('staging_id', sa.String(), nullable=True),
        sa.Column('src_entity_cd', sa.String(), nullable=False),
        sa.Column('src_booking_dept_cd', sa.String(), nullable=False),
        sa.Column('src_account_id', sa.String(), nullable=False),
        sa.Column('src_account_nm', sa.String(), nullable=False),
        sa.Column('src_acct_category', sa.String(), nullable=False),
        sa.Column('src_acct_type', sa.String(), nullable=False),
        sa.Column('norm_acct_sign', sa.String(), nullable=False),
        sa.Column('total_acct_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('acct_func_sign', sa.String(), nullable=False),
        sa.Column('src_client_id', sa.String(), nullable=True),
        sa.Column('src_client_nm', sa.String(), nullable=True),
        sa.Column('entity_sun_id', sa.String(), nullable=True),
        sa.Column('cpty_ref_id', sa.String(), nullable=True),
        sa.Column('client_id_type', sa.String(), nullable=True),
        sa.Column('intergroup_ind', sa.String(), nullable=True),
        sa.Column('src_measure_nm', sa.String(), nullable=False),
        sa.Column('src_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('src_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('posting_measure_nm', sa.String(), nullable=True),
        sa.Column('measure_type', sa.String(), nullable=True),
        sa.Column('posting_measure_func_ccy_cd', sa.String(), nullable=True),
        sa.Column('posting_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('fx_rate', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('cr_dr_evaluator', sa.String(), nullable=True),

        schema='foundry_staging',
    )

    op.create_table(
        'trial_balance',

        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('extract_dt', sa.Date(), nullable=False),
        sa.Column('as_of_dt', sa.Date(), nullable=False),
        sa.Column('business_dt', sa.Date(), nullable=False),
        sa.Column('src_app_cd', sa.String(), nullable=False),
        sa.Column('src_app_nm', sa.String(), nullable=False),
        sa.Column('dataclass', sa.String(), nullable=True),
        sa.Column('src_record_id', sa.String(), nullable=False),
        sa.Column('staging_id', sa.String(), nullable=True),
        sa.Column('enrichment_id', sa.String(), nullable=True),
        sa.Column('src_entity_cd', sa.String(), nullable=False),
        sa.Column('src_booking_dept_cd', sa.String(), nullable=False),
        sa.Column('src_account_id', sa.String(), nullable=False),
        sa.Column('src_account_nm', sa.String(), nullable=False),
        sa.Column('src_acct_category', sa.String(), nullable=False),
        sa.Column('src_acct_type', sa.String(), nullable=False),
        sa.Column('norm_acct_sign', sa.String(), nullable=False),
        sa.Column('total_acct_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('acct_func_sign', sa.String(), nullable=False),
        sa.Column('src_client_id', sa.String(), nullable=True),
        sa.Column('src_client_nm', sa.String(), nullable=True),
        sa.Column('entity_sun_id', sa.String(), nullable=True),
        sa.Column('cpty_ref_id', sa.String(), nullable=True),
        sa.Column('client_id_type', sa.String(), nullable=True),
        sa.Column('intergroup_ind', sa.String(), nullable=True),
        sa.Column('src_measure_nm', sa.String(), nullable=False),
        sa.Column('src_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('src_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('posting_measure_nm', sa.String(), nullable=True),
        sa.Column('measure_type', sa.String(), nullable=True),
        sa.Column('posting_measure_func_ccy_cd', sa.String(), nullable=True),
        sa.Column('posting_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('fx_rate', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('cr_dr_evaluator', sa.String(), nullable=True),
        sa.Column('cr_dr_ind', sa.String(), nullable=True),
        sa.Column('posting_rule_id', sa.String(), nullable=True),
        sa.Column('rule_id_desc', sa.String(), nullable=True),
        sa.Column('posting_stream', sa.String(), nullable=True),
        sa.Column('posting_switch', sa.String(), nullable=True),
        sa.Column('measure_period_type', sa.String(), nullable=True),
        sa.Column('posting_elig_flg', sa.String(), nullable=True),
        sa.Column('je_desc', sa.String(), nullable=True),
        sa.Column('event_type_cd', sa.String(), nullable=True),
        sa.Column('trans_group_prefix', sa.String(), nullable=True),
        sa.Column('trans_dt', sa.String(), nullable=True),
        sa.Column('trans_no', sa.String(), nullable=True),
        sa.Column('line_no', sa.String(), nullable=True),
        sa.Column('coa_rule_id', sa.String(), nullable=True),
        sa.Column('gl_entity_cd', sa.String(), nullable=True),
        sa.Column('gl_dept_cd', sa.String(), nullable=True),
        sa.Column('gl_branch_cd', sa.String(), nullable=True),
        sa.Column('gl_account_dr', sa.String(), nullable=True),
        sa.Column('gl_account_dr_desc', sa.String(), nullable=True),
        sa.Column('gl_account_cr', sa.String(), nullable=True),
        sa.Column('gl_account_cr_desc', sa.String(), nullable=True),
        sa.Column('gl_account', sa.String(), nullable=True),
        sa.Column('gl_sub_account', sa.String(), nullable=True),
        sa.Column('gl_affiliate_cd', sa.String(), nullable=True),
        sa.Column('gl_product_cd', sa.String(), nullable=True),
        sa.Column('gl_book_cd', sa.String(), nullable=True),
        sa.Column('gl_coa_src_segment', sa.String(), nullable=True),

        schema='foundry_enrichment',
    )

    op.create_table(
        'trial_balance',

        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('extract_dt', sa.Date(), nullable=False),
        sa.Column('as_of_dt', sa.Date(), nullable=False),
        sa.Column('business_dt', sa.Date(), nullable=False),
        sa.Column('src_app_cd', sa.String(), nullable=False),
        sa.Column('src_app_nm', sa.String(), nullable=False),
        sa.Column('dataclass', sa.String(), nullable=True),
        sa.Column('src_record_id', sa.String(), nullable=False),
        sa.Column('staging_id', sa.String(), nullable=True),
        sa.Column('enrichment_id', sa.String(), nullable=True),
        sa.Column('reporting_id', sa.String(), nullable=True),
        sa.Column('src_entity_cd', sa.String(), nullable=False),
        sa.Column('src_booking_dept_cd', sa.String(), nullable=False),
        sa.Column('src_account_id', sa.String(), nullable=False),
        sa.Column('src_account_nm', sa.String(), nullable=False),
        sa.Column('src_acct_category', sa.String(), nullable=False),
        sa.Column('src_acct_type', sa.String(), nullable=False),
        sa.Column('norm_acct_sign', sa.String(), nullable=False),
        sa.Column('total_acct_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('acct_func_sign', sa.String(), nullable=False),
        sa.Column('src_client_id', sa.String(), nullable=True),
        sa.Column('src_client_nm', sa.String(), nullable=True),
        sa.Column('entity_sun_id', sa.String(), nullable=True),
        sa.Column('cpty_ref_id', sa.String(), nullable=True),
        sa.Column('client_id_type', sa.String(), nullable=True),
        sa.Column('intergroup_ind', sa.String(), nullable=True),
        sa.Column('src_measure_nm', sa.String(), nullable=False),
        sa.Column('src_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('src_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('posting_measure_nm', sa.String(), nullable=True),
        sa.Column('measure_type', sa.String(), nullable=True),
        sa.Column('posting_measure_func_ccy_cd', sa.String(), nullable=True),
        sa.Column('posting_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('fx_rate', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('cr_dr_evaluator', sa.String(), nullable=True),
        sa.Column('cr_dr_ind', sa.String(), nullable=True),
        sa.Column('posting_rule_id', sa.String(), nullable=True),
        sa.Column('rule_id_desc', sa.String(), nullable=True),
        sa.Column('posting_stream', sa.String(), nullable=True),
        sa.Column('posting_switch', sa.String(), nullable=True),
        sa.Column('measure_period_type', sa.String(), nullable=True),
        sa.Column('posting_elig_flg', sa.String(), nullable=True),
        sa.Column('je_desc', sa.String(), nullable=True),
        sa.Column('event_type_cd', sa.String(), nullable=True),
        sa.Column('trans_group_prefix', sa.String(), nullable=True),
        sa.Column('trans_dt', sa.String(), nullable=True),
        sa.Column('trans_no', sa.String(), nullable=True),
        sa.Column('line_no', sa.String(), nullable=True),
        sa.Column('coa_rule_id', sa.String(), nullable=True),
        sa.Column('gl_entity_cd', sa.String(), nullable=True),
        sa.Column('gl_dept_cd', sa.String(), nullable=True),
        sa.Column('gl_branch_cd', sa.String(), nullable=True),
        sa.Column('gl_account_dr', sa.String(), nullable=True),
        sa.Column('gl_account_dr_desc', sa.String(), nullable=True),
        sa.Column('gl_account_cr', sa.String(), nullable=True),
        sa.Column('gl_account_cr_desc', sa.String(), nullable=True),
        sa.Column('gl_account', sa.String(), nullable=True),
        sa.Column('gl_sub_account', sa.String(), nullable=True),
        sa.Column('gl_affiliate_cd', sa.String(), nullable=True),
        sa.Column('gl_product_cd', sa.String(), nullable=True),
        sa.Column('gl_book_cd', sa.String(), nullable=True),
        sa.Column('gl_coa_src_segment', sa.String(), nullable=True),

        schema='foundry_reporting',
    )

    op.create_table(
        'trial_balance',

        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('extract_dt', sa.Date(), nullable=False),
        sa.Column('as_of_dt', sa.Date(), nullable=False),
        sa.Column('business_dt', sa.Date(), nullable=False),
        sa.Column('src_app_cd', sa.String(), nullable=False),
        sa.Column('src_app_nm', sa.String(), nullable=False),
        sa.Column('dataclass', sa.String(), nullable=True),
        sa.Column('src_record_id', sa.String(), nullable=False),
        sa.Column('staging_id', sa.String(), nullable=True),
        sa.Column('enrichment_id', sa.String(), nullable=True),
        sa.Column('reporting_id', sa.String(), nullable=True),
        sa.Column('posting_id', sa.String(), nullable=True),
        sa.Column('src_entity_cd', sa.String(), nullable=False),
        sa.Column('src_booking_dept_cd', sa.String(), nullable=False),
        sa.Column('src_account_id', sa.String(), nullable=False),
        sa.Column('src_account_nm', sa.String(), nullable=False),
        sa.Column('src_acct_category', sa.String(), nullable=False),
        sa.Column('src_acct_type', sa.String(), nullable=False),
        sa.Column('norm_acct_sign', sa.String(), nullable=False),
        sa.Column('total_acct_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('acct_func_sign', sa.String(), nullable=False),
        sa.Column('src_client_id', sa.String(), nullable=True),
        sa.Column('src_client_nm', sa.String(), nullable=True),
        sa.Column('entity_sun_id', sa.String(), nullable=True),
        sa.Column('cpty_ref_id', sa.String(), nullable=True),
        sa.Column('client_id_type', sa.String(), nullable=True),
        sa.Column('intergroup_ind', sa.String(), nullable=True),
        sa.Column('src_measure_nm', sa.String(), nullable=False),
        sa.Column('src_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('src_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_ccy_cd', sa.String(), nullable=False),
        sa.Column('posting_measure_nm', sa.String(), nullable=True),
        sa.Column('measure_type', sa.String(), nullable=True),
        sa.Column('posting_measure_func_ccy_cd', sa.String(), nullable=True),
        sa.Column('posting_measure_trans_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('fx_rate', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_measure_func_amt', sa.Numeric(28, 12), nullable=False),
        sa.Column('cr_dr_evaluator', sa.String(), nullable=True),
        sa.Column('cr_dr_ind', sa.String(), nullable=True),
        sa.Column('posting_rule_id', sa.String(), nullable=True),
        sa.Column('rule_id_desc', sa.String(), nullable=True),
        sa.Column('posting_stream', sa.String(), nullable=True),
        sa.Column('posting_switch', sa.String(), nullable=True),
        sa.Column('measure_period_type', sa.String(), nullable=True),
        sa.Column('posting_elig_flg', sa.String(), nullable=True),
        sa.Column('je_desc', sa.String(), nullable=True),
        sa.Column('event_type_cd', sa.String(), nullable=True),
        sa.Column('trans_group_prefix', sa.String(), nullable=True),
        sa.Column('trans_dt', sa.String(), nullable=True),
        sa.Column('trans_no', sa.String(), nullable=True),
        sa.Column('line_no', sa.String(), nullable=True),
        sa.Column('coa_rule_id', sa.String(), nullable=True),
        sa.Column('gl_entity_cd', sa.String(), nullable=True),
        sa.Column('gl_dept_cd', sa.String(), nullable=True),
        sa.Column('gl_branch_cd', sa.String(), nullable=True),
        sa.Column('gl_account_dr', sa.String(), nullable=True),
        sa.Column('gl_account_dr_desc', sa.String(), nullable=True),
        sa.Column('gl_account_cr', sa.String(), nullable=True),
        sa.Column('gl_account_cr_desc', sa.String(), nullable=True),
        sa.Column('gl_account', sa.String(), nullable=True),
        sa.Column('gl_sub_account', sa.String(), nullable=True),
        sa.Column('gl_affiliate_cd', sa.String(), nullable=True),
        sa.Column('gl_product_cd', sa.String(), nullable=True),
        sa.Column('gl_book_cd', sa.String(), nullable=True),
        sa.Column('gl_coa_src_segment', sa.String(), nullable=True),
        sa.Column('previous_day_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('current_day_debit_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('current_day_credit_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('current_day_eod_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('back_value_adjusted_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('adjusted_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_previous_day_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_current_day_debit_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_current_day_credit_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_current_day_eod_balance', sa.Numeric(28, 12), nullable=False),
        sa.Column('posting_back_value_adjusted_balance', sa.Numeric(28, 12), nullable=True),
        sa.Column('posting_adjusted_balance', sa.Numeric(28, 12), nullable=False),

        schema='foundry_posting',
    )


def downgrade() -> None:
    op.drop_table('trial_balance', schema='foundry_posting')
    op.drop_table('trial_balance', schema='foundry_reporting')
    op.drop_table('trial_balance', schema='foundry_enrichment')
    op.drop_table('trial_balance', schema='foundry_staging')
