from unittest.mock import MagicMock

from foundry.models import PipelineConfig
from foundry.pipeline.base import BasePipeline

from tests.support.constants import BUSINESS_DT


class NoOpPipeline(BasePipeline):
    '''A BasePipeline whose every hook is a no-op. Zone tests subclass it
    and override only the hooks of the zone under test.'''

    def pre_staging(self): ...
    def main_staging(self, df): ...
    def post_staging(self, df): ...
    def pre_enrichment(self, workflow_run_id): ...
    def main_enrichment(self, df): ...
    def post_enrichment(self, df): ...
    def pre_reporting(self, workflow_run_id): ...
    def main_reporting(self, df): ...
    def post_reporting(self, df): ...
    def pre_posting(self, workflow_run_id): ...
    def main_posting(self, df): ...
    def post_posting(self, df): ...
    def pre_interface(self, workflow_run_id): ...
    def main_interface(self, df): ...
    def post_interface(self, df): ...


def make_pipeline(pipeline_cls=NoOpPipeline, **kwargs) -> NoOpPipeline:
    return pipeline_cls(
        config=PipelineConfig(
            dataclass='TRIAL_BALANCE',
            business_dt=BUSINESS_DT,
        ),
        atlas=MagicMock(),
        reference=MagicMock(),
        spec=MagicMock(),
        **kwargs,
    )
